#!/bin/env bash

file=$1
# stroke or fill
option=$2
#color
color=$3
#ouput
output=$4

if [ -z "$file" ] || [ -z "$option" ] || [ -z "$color" ] || [ -z "$output" ]; then
	echo "Missing options"
	exit 1
fi


cp $file $output


sed -E -i "s/$option=\"#?[a-zA-Z0-9]+\"/$option=\"$color\"/" $output
sed -E -i "s/$option:#?[a-zA-Z0-9]+;/$option:$color;/" $output
